const { Router } = require('express')
const bodyParser = require('body-parser')
const { login, verify, newuser, updateuser, listunitats, list, getcentre, getunitat, getarea, listcentres, liststock, newstock, updatestock, removestock, getdate } = require('./handlers')
const router = Router()
const jsonBodyParser = bodyParser.json()

router.post('/login', jsonBodyParser, login)
router.post('/verify', jsonBodyParser, verify)
router.get('/newuser', newuser)
router.put('/updateuser', jsonBodyParser, updateuser)
router.get('/unitat', listunitats)
router.get('/users', list)
router.get('/centre', getcentre)
router.get('/getunitat', getunitat)
router.get('/area', getarea)
router.get('/centres', listcentres)
router.get('/stock', liststock)
router.get('/newstock', newstock)
router.get('/updatestock', updatestock)
router.delete('/removestock', removestock)
router.get('/getdate', getdate)

module.exports = router